# Website settings
title: "Doug Milvaney"
description: "Hi, I'm Doug and I like improving people's lives through technology."
#keywords: "Jack,Jalpc,blog,Jekyll,github,gh-pages"
baseurl: "/"
url: ""
# url: "http://127.0.0.1:4000"

# author
author:
  name: 'Doug Milvaney'
  first_name: 'Doug'
  last_name: 'Milvaney'
  email: 'doug@dougmilvaney.com'
  github_username: 'dmilvaney'
  twitter_username: 'dmilvaney'
  linkedin_username: 'dmilvaney'
  medium_username: 'dmilvaney'
  producthunt_username: 'dmilvaney'
  head_img: 'static/img/landing/doug.jpg'
  bio_short: Hi, I'm Doug and I like improving people's lives through technology.
  bio_long: Specifically, I'm passionate about listening to and learning from people to understand what problems they have and how I can help solve them. When I'm not immersed in product development and technology, you can find me <a href="https://www.goodreads.com/dmilvaney/" target="blank">reading 📖</a>, <a href="https://www.coursera.org/user/ad11c403c52086f190dd5fd87941de43" target="blank">learning 🧠</a>, <a href="http://brooklynboulders.com/somerville/" target="blank">rock climbing 🧗‍</a>, <a href="http://www.adk46er.org/" target="blank">hiking</a> 🏔, cycling 🚴‍, skiing ⛷, staying active (🧘‍, 🏋️‍, 🏌️‍, ⛹️‍, 🎣), or attempting to craft the perfect cocktail 🥃 or brew my own beer 🍺.
  suggest_email: 'suggest@dougmilvaney.com'

# landing page
landing:
  home: 'Home'
  about: 'About'
  career: 'Career'
  projects: 'Projects'
  learning: 'Learning'
  portfolio: 'Portfolio'

# my projects
project:
  activity:
    name: 'Activity Feed'
    url: 'https://blogs.office.com/2016/04/26/new-to-office-365-in-april-skype-for-business-mac-preview-bringing-collaboration-to-the-forefront-in-office-and-more/'
    img: 'static/img/portfolio/activity_feed.png'
  history:
    name: 'Version History'
    url: 'https://blogs.office.com/2015/10/22/history-collaborate-with-confidence/'
    img:
      one: 'static/img/portfolio/history_and.png'
      two: 'static/img/portfolio/history_win32.png'
  autosave:
    name: 'Auto-Save UI'
    url: ''
    img: ''
  giv2giv:
    name: 'giv2giv'
    url: 'https://giv2giv.org/'
    img: 'static/img/landing/g2g.jpg'
    proj: 'static/img/portfolio/giv2giv_projections.png'
    tech_paper_url: '../static/pdf/giv2giv_technical_paper.pdf'
    program_ref_url: '../static/pdf/giv2giv_programming_reference.pdf'
    user_manual_url: '../static/pdf/giv2giv_user_manual.pdf'
  vistandes:
    name: 'Vistandes'
    url: 'http://www.vistandes.com/'
    img: 'static/img/landing/vistandes.jpg'
    emp: 'static/img/portfolio/vistandes_employee_page.png'

# my learnings
learnings:
  book_one:
    name: 'Shoe Dog: A Memoir by the Creator of Nike'
    author: 'Phil Knight'
    url: 'https://www.amazon.com/Shoe-Dog-Memoir-Creator-Nike-ebook/dp/B0176M1A44/ref=sr_1_1?s=digital-text&ie=UTF8&qid=1485397082&sr=1-1&keywords=shoe+dog'
    img: 'static/img/landing/shoe_dog.jpg'
  book_two:
    name: 'Lean Analytics: Use Data to Build a Better Startup Faster '
    author: 'Alistair Croll & Benjamin Yoskovitz'
    url: 'https://www.amazon.com/Lean-Analytics-Better-Startup-Faster-ebook/dp/B00AG66LTM/ref=sr_1_1?s=digital-text&ie=UTF8&qid=1472745154&sr=1-1&keywords=lean+analytics#nav-subnav'
    img: 'static/img/landing/lean_analytics.jpg'
  book_three:
    name: 'From Impossible to Inevitable: How Hyper-Growth Companies Create Predictable Revenue'
    author: 'Aaron Ross & Jason Lemkin'
    url: 'https://www.amazon.com/Impossible-Inevitable-Hyper-Growth-Companies-Predictable-ebook/dp/B01AXTFMSW/ref=sr_1_1?s=digital-text&ie=UTF8&qid=1485396794&sr=1-1&keywords=from+impossible+to+inevitable'
    img: 'static/img/landing/impossible_inevitable.jpg'
  book_four:
    name: 'Food & Beer'
    author: 'Daniel Burns, Jeppe Jarnit-Bjergso, & Joshua David Stein'
    url: 'https://www.amazon.com/Food-Beer-Daniel-Burns/dp/0714871052/ref=sr_1_1?s=books&ie=UTF8&qid=1472770858&sr=1-1&keywords=food+and+beer'
    img: 'static/img/landing/food_&_beer.jpg'
  podcast_one:
    name: 'Seeking Wisdom'
    author: 'David Cancel & Dave Gerhardt'
    url: 'https://seekingwisdom.io/tagged/podcast'
    img: 'static/img/landing/seeking_wisdom.jpg'
  podcast_two:
    name: 'a16z'
    author: 'a16z'
    url: 'http://a16z.com/podcasts/'
    img: 'static/img/landing/a16z.jpg'
  podcast_three:
    name: 'StartUp Podcasat'
    author: 'Gimlet Media'
    url: 'https://itunes.apple.com/us/podcast/startup-podcast/id913805339?mt=2'
    img: 'static/img/landing/startup.jpg'
  podcast_four:
    name: 'Good Beer Hunting'
    author: 'Michael Kiser'
    url: 'http://goodbeerhunting.com/gbh-podcast/'
    img: 'static/img/landing/good_beer_hunting.jpg'
  class_one:
    name: 'Machine Learning'
    organization: 'Stanford University'
    url: 'https://www.coursera.org/account/accomplishments/certificate/UDAS3WQ39GZ6'
    img: ''
# recently read & upcoming books
books:
  read:
    one:
      name: 'Hooked: How to Build Habit-Forming Products'
      url: 'https://smile.amazon.com/Hooked-How-Build-Habit-Forming-Products-ebook/dp/B00LMGLXTS/ref=sr_1_1_twi_kin_2?ie=UTF8&qid=1473811861&sr=8-1&keywords=hooked#nav-subnav'
    two:
      name: 'The Life-Changing Magic of Tidying Up: The Japanese Art of Decluttering and Organizing'
      url: 'https://smile.amazon.com/Life-Changing-Magic-Tidying-Decluttering-Organizing-ebook/dp/B00KK0PICK/ref=sr_1_1?s=digital-text&ie=UTF8&qid=1473811945&sr=1-1&keywords=the+life+changing+magic+of+tidying+up#nav-subnav'
    three:
      name: 'Managing Oneself'
      url: 'https://smile.amazon.com/Managing-Oneself-Harvard-Business-Classics-ebook/dp/B00TXS49UW/ref=sr_1_1_twi_kin_1?s=books&ie=UTF8&qid=1473812031&sr=1-1&keywords=managing+oneself#nav-subnav'
  upcoming:
    one:
      name: 'From Impossible To Inevitable: How Hyper-Growth Companies Create Predictable Revenue'
      url: 'https://smile.amazon.com/Impossible-Inevitable-Hyper-Growth-Companies-Predictable-ebook/dp/B01AXTFMSW/ref=sr_1_1_twi_kin_1?s=books&ie=UTF8&qid=1473812091&sr=1-1&keywords=from+impossible+to+inevitable#nav-subnav'
    two:
      name: 'Running Lean: Iterate from Plan A to a Plan That Works'
      url: 'https://smile.amazon.com/dp/B006UKFFE0/ref=wl_it_dp_o_pC_nS_ttl?_encoding=UTF8&colid=2WKFHAEZZ0PSQ&coliid=INJWAIDEX9IW3#nav-subnav'
    three:
      name: 'Shoe Dog: A Memoir by the Creator of Nike'
      url: 'https://smile.amazon.com/Shoe-Dog-Memoir-Creator-Nike-ebook/dp/B0176M1A44/ref=sr_1_1?s=digital-text&ie=UTF8&qid=1473812236&sr=1-1&keywords=shoe+dog#nav-subnav'

# google analytics
#ga:
  #id: UA-73784599-1

# Build settings
encoding: "utf-8"

# other settings
highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
