# Website settings
title: "Doug Milvaney"
description: "Hi I'm Doug and I like building awesome products."
#keywords: "Jack,Jalpc,blog,Jekyll,github,gh-pages"
baseurl: "/"
url: ""
# url: "http://127.0.0.1:4000"

# author
author:
  name: 'Doug Milvaney'
  first_name: 'Doug'
  last_name: 'Milvaney'
  email: 'dlm2dh@gmail.com'
  github_username: 'dlm2dh'
  twitter_username: 'dmilvaney'
  linkedin_username: 'dmilvaney'
  medium_username: 'dmilvaney'
  producthunt_username: 'dmilvaney'

  head_img: 'static/img/landing/doug.jpg'

# landing page
landing:
  home: 'Home'
  about: 'About'
  career: 'Career'
  skills: 'Skills'
  projects: 'Projects'
  learning: 'Learning'
  portfolio: 'Portfolio'
  blog: 'Blog'

# my projects
project:
  activity:
    name: 'Activity Feed'
    url: 'https://blogs.office.com/2016/04/26/new-to-office-365-in-april-skype-for-business-mac-preview-bringing-collaboration-to-the-forefront-in-office-and-more/'
    img: 'static/img/portfolio/activity_feed.png'
  giv2giv:
    name: 'giv2giv'
    url: 'https://giv2giv.org/'
    img: 'static/img/landing/g2g.jpg'
  vistandes:
    name: 'Vistandes'
    url: 'http://www.vistandes.com/'
    img: 'static/img/landing/vistandes.jpg'
  angularjs:
    name: 'Jalpc-A'
    url: '/Jack614/Jalpc-A'
    img: 'static/img/landing/angularjs.png'
  Rsser:
    name: 'Rsser'
    url: '/Jack614/Rsser'
    img: 'static/img/landing/rsser.png'

# my learnings
learnings:
  book_one:
    name: 'Quench Your Own Thirst'
    author: 'Jim Koch'
    url: 'https://www.amazon.com/Quench-Your-Own-Thirst-Business-ebook/dp/B0166RX444/ref=sr_1_1?s=digital-text&ie=UTF8&qid=1472733553&sr=1-1&keywords=quench+your+own+thirst#nav-subnav'
    img: 'static/img/landing/quench_your_own_thirst.jpg'
  book_two:
    name: 'Lean Analytics'
    author: 'Alistair Croll & Benjamin Yoskovitz'
    url: 'https://www.amazon.com/Lean-Analytics-Better-Startup-Faster-ebook/dp/B00AG66LTM/ref=sr_1_1?s=digital-text&ie=UTF8&qid=1472745154&sr=1-1&keywords=lean+analytics#nav-subnav'
    img: 'static/img/landing/lean_analytics.jpg'
  book_three:
    name: 'The Hard Thing About Hard Things'
    author: 'Ben Horowitz'
    url: 'https://www.amazon.com/s/ref=nb_sb_ss_c_1_13?url=search-alias%3Ddigital-text&field-keywords=the+hard+thing+about+hard+things&sprefix=the+hard+thin%2Cdigital-text%2C143'
    img: 'static/img/landing/the_hard_thing_about_hard_things.jpg'
  book_four:
    name: 'Food & Beer'
    author: 'Daniel Burns, Jeppe Jarnit-Bjergso, & Joshua David Stein'
    url: 'https://www.amazon.com/Food-Beer-Daniel-Burns/dp/0714871052/ref=sr_1_1?s=books&ie=UTF8&qid=1472770858&sr=1-1&keywords=food+and+beer'
    img: 'static/img/landing/food_&_beer.jpg'
  podcast_one:
    name: 'Seeking Wisdom'
    author: 'David Cancel & Dave Gerhardt'
    url: 'https://seekingwisdom.io/tagged/podcast'
    img: 'static/img/landing/seeking_wisdom.jpg'
  podcast_two:
    name: 'a16z'
    author: 'a16z'
    url: 'http://a16z.com/podcasts/'
    img: 'static/img/landing/a16z.jpg'
  podcast_three:
    name: 'Tech In Boston'
    author: 'Dave Gerhardt'
    url: 'https://itunes.apple.com/us/podcast/tech-in-boston/id855347254?mt=2'
    img: 'static/img/landing/tech_in_boston.jpg'
  podcast_four:
    name: 'Good Beer Hunting'
    author: 'Michael Kiser'
    url: 'http://goodbeerhunting.com/gbh-podcast/'
    img: 'static/img/landing/good_beer_hunting.jpg'

# google analytics
#ga:
  #id: UA-73784599-1

# Build settings
encoding: "utf-8"

# other settings
highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
