# Website settings
title: "Doug Milvaney"
description: "Hi I'm Doug and I like building awesome products."
#keywords: "Jack,Jalpc,blog,Jekyll,github,gh-pages"
baseurl: "/"
url: ""
# url: "http://127.0.0.1:4000"

# blog img path
img_path: 'http://www.jack003.com/static/img/blog'

# author
author:
  name: 'Doug Milvaney'
  first_name: 'Doug'
  last_name: 'Milvaney'
  email: 'dlm2dh@gmail.com'
  #facebook_username: 'jiakunnj'
  github_username: 'dlm2dh'
  twitter_username: dmilvaney
  head_img: 'static/img/landing/Jack.jpg'

# landing page
landing:
  home: 'Home'
  about: 'About'
  career: 'Career'
  skills: 'Skills'
  projects: 'Project'
  blog: 'Blog'
  link: 'Link'

# my projects
project:
  saplatform:
    name: 'Saplatform'
    url: '/Jack614/saplatform'
    img: 'static/img/landing/saplatform.png'
  jalpc:
    name: 'Jalpc'
    url: '/Jack614/jalpc_jekyll_theme'
    img: 'static/img/landing/jekyll.png'
  angularjs:
    name: 'Jalpc-A'
    url: '/Jack614/Jalpc-A'
    img: 'static/img/landing/angularjs.png'
  Rsser:
    name: 'Rsser'
    url: '/Jack614/Rsser'
    img: 'static/img/landing/rsser.png'

# blog index
index:
  home: 'Home'
  python: 'Python'
  linux: 'Linux'
  html: 'HTML'
  database: 'Database'
  mac: 'Mac'
  life: 'Life'

# donate
donate:
  wechat: 'static/img/pay/wechat.png'
  alipay: 'static/img/pay/alipay.png'

# google analytics
#ga:
  #id: UA-73784599-1

# Build settings
encoding: "utf-8"

# other settings
highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
