# Website settings
title: "Doug Milvaney"
description: "Hi I'm Doug and I like building awesome products."
#keywords: "Jack,Jalpc,blog,Jekyll,github,gh-pages"
baseurl: "/"
url: ""
# url: "http://127.0.0.1:4000"

# author
author:
  name: 'Doug Milvaney'
  first_name: 'Doug'
  last_name: 'Milvaney'
  email: 'dlm2dh@gmail.com'
  github_username: 'dlm2dh'
  twitter_username: 'dmilvaney'
  head_img: 'static/img/landing/doug.jpg'

# landing page
landing:
  home: 'Home'
  about: 'About'
  career: 'Career'
  skills: 'Skills'
  projects: 'Projects'
  learning: 'Learning'
  blog: 'Blog'

# my projects
project:
  saplatform:
    name: 'Saplatform'
    url: '/Jack614/saplatform'
    img: 'static/img/landing/saplatform.png'
  jalpc:
    name: 'Jalpc'
    url: '/Jack614/jalpc_jekyll_theme'
    img: 'static/img/landing/jekyll.png'
  angularjs:
    name: 'Jalpc-A'
    url: '/Jack614/Jalpc-A'
    img: 'static/img/landing/angularjs.png'
  Rsser:
    name: 'Rsser'
    url: '/Jack614/Rsser'
    img: 'static/img/landing/rsser.png'

# my learnings
learnings:
  book_one:
    name: 'Quench Your Own Thirst'
    author: 'Jim Koch'
    url: 'https://www.amazon.com/Quench-Your-Own-Thirst-Business-ebook/dp/B0166RX444/ref=sr_1_1?s=digital-text&ie=UTF8&qid=1472733553&sr=1-1&keywords=quench+your+own+thirst#nav-subnav'
    img: 'static/img/landing/quench_your_own_thirst.jpg'
  book_two:
    name: 'Lean Analytics'
    author: 'Alistair Croll & Benjamin Yoskovitz'
    url: 'https://www.amazon.com/Lean-Analytics-Better-Startup-Faster-ebook/dp/B00AG66LTM/ref=sr_1_1?s=digital-text&ie=UTF8&qid=1472745154&sr=1-1&keywords=lean+analytics#nav-subnav'
    img: 'static/img/landing/lean_analytics.jpg'
  book_three:
    name: 'The Hard Thing About Hard Things'
    author: 'Ben Horowitz'
    url: 'https://www.amazon.com/s/ref=nb_sb_ss_c_1_13?url=search-alias%3Ddigital-text&field-keywords=the+hard+thing+about+hard+things&sprefix=the+hard+thin%2Cdigital-text%2C143'
    img: 'static/img/landing/the_hard_thing_about_hard_things.jpg'
  book_four:
    name: 'Food & Beer'
    author: 'Daniel Burns, Jeppe Jarnit-Bjergso, & Joshua David Stein'
    url: 'https://www.amazon.com/Food-Beer-Daniel-Burns/dp/0714871052/ref=sr_1_1?s=books&ie=UTF8&qid=1472770858&sr=1-1&keywords=food+and+beer'
    img: 'static/img/landing/food_&_beer.jpg'

# blog index
index:
  home: 'Home'
  python: 'Python'
  linux: 'Linux'
  html: 'HTML'
  database: 'Database'
  mac: 'Mac'
  life: 'Life'

# google analytics
#ga:
  #id: UA-73784599-1

# Build settings
encoding: "utf-8"

# other settings
highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
